<?php 
$this->title = "Manage Contents";
$this->headTitle($this->title);
?>
<p><a class="btn-add-admin btn btn-success" href="<?php echo $this->url(array('controller'=>'index',
'action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Add new Content</a></p>
<table class="table table-striped table-hover">
	<thead>
	<tr>
		<th>Id</th>
		<th>Title</th>
		<th width="68">Status</th>
		<th width="100">Date</th>
		<th width="150">Operations</th>
	</tr>
	</thead>
	
	<tbody>
	<?php foreach($this->contents as $content) : ?>
	<?php
	$pubsts = $content->published ? 
		'<span class="glyphicon glyphicon-ok" title="published"></span>' : 
		'<span class="glyphicon glyphicon-remove" title="Unpublished"></span>' ;
	?>
	<tr>
		<td><?php echo $this->escape($content->id);?></td>
		<td><?php echo $this->escape($content->title);?></td>
		<td align="center"><?php echo $pubsts;?></td>
		<td><?php echo $this->escape(date('Y/m/d', strtotime($content->pubdate)));?></td>
		<td class="opr">
			<a class="label label-info" href="<?php echo $this->url(array('controller'=>'index',
			'action'=>'edit', 'id'=>$content->id));?>">
				<span class="glyphicon glyphicon-pencil"></span> 
				Edit
			</a> 
			
			<a class="label label-danger" href="<?php echo $this->url(array('controller'=>'index',
			'action'=>'delete', 'id'=>$content->id));?>">
				<span class="glyphicon glyphicon-remove"></span> 
				Delete
			</a>
			
			<!--
			<a class="label label-warning" href="<?php echo $this->url(array('controller'=>'index',
			'action'=>'delete', 'id'=>$content->id));?>">
				<span class="glyphicon glyphicon-certificate"></span> 
				Publish
			</a>
			-->
		</td>
	</tr>
	<?php endforeach; ?>
	</tbody>
	
</table>